name: Publish to PyPI on release

on:
  release:
    types: [published]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install build dependencies
        run: python -m pip install --upgrade build twine
        
      - name: Build package
        run: python -m build
        
      - name: Publish to PyPI
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}